### ISSUE TITLE
Set default relay state?

### ISSUE THREAD

**Issue by mjg59** [jimpastos/wink-relay-manager#1]
I'd like the relays to default to on in the event of a power cut - could support for this be added to the config file?

**Comment by jimpastos** [comment]
Yeap, great idea. There should be a default (no change), on and off initial states.

**Comment by jimpastos** [comment]
Done.
New config values:
initial_relay_upper_state=1 // (1, yes or true)...
initial_relay_lower_state=false // (0, no or false)...

**Comment by mjg59** [comment]
Thanks!
