### ISSUE TITLE
Allow controlling the screen

### ISSUE THREAD

**Issue by jrfernandes** [jimpastos/wink-relay-manager#10]
It would be great if it would be possible to control the screen as well. The SmartThings _integration_ makes it sound that this is possible: 

https://community.smartthings.com/t/beta-wink-relay-custom-smartthings-integration/111732
> **Screen Backlight Control**
> The screen backlight can be controlled with the screenBacklightOn() and > screenBacklightOff() commands. These can be called from other custom SmartApps like WebCoRE or SharpTools.

**Comment by jimpastos** [comment]
You can. Look at the control topics section on the readme.
Sending a payload to <MQTTPrefix>/screen/ should allow you to turn the screen on/off

**Comment by jrfernandes** [comment]
Nice. Thank you and great work. :+1:
