### ISSUE TITLE
Rename topics topics and data to match Home Assistant?

### ISSUE THREAD

**Issue by cyberbobcity** [jimpastos/wink-relay-manager#12]
Curious if it's ever been brought up to change the topics and data to match items for Home Assistant's MQTT Discovery?

Relays would need to be renamed to Switches. Some of the msg's would need to be changed to match that format.

I was thinking about giving it a try. I'm pretty new to HA and MQTT, and offering the relay's as switches in HA would be great!

Thanks for all your hard work! I was able to get my Wink Relay working tonight with this package!

**Comment by jimpastos** [comment]
Havent looked into HA mqtt discovery, but HA works fine with MQTT Light/Fan with their corresponding control and state topics.

**Comment by cyberbobcity** [comment]
I got just a basic manual config working late last night and setup my MQTT switches in a new switches.yaml which is connected to the main configuration.yaml. So yea, no need for the discovery. Just required a little config.

Thanks for the quick response! Awesome app! Now I just need to see about what I should do on the Wink Relay screen. Some people have mentioned HADashboard.

**Comment by jimpastos** [comment]
I personally have a full screen chrome browser (shortcut on home screen) into a direct lovelace tab

**Comment by cyberbobcity** [comment]
Ok gotcha. I guess that would be easier.

**Comment by cyberbobcity** [comment]
Could you tell me how you got chrome installed? Mine says it’s not compatible… Firefox doesn’t seem to have a full screen feature and none of the full screen browsers I tried worked. Nor did installing Ariela.

**Comment by jimpastos** [comment]
Install PureAPK which had Google Chrome there. Not sure if the latest version is not supported anymore

**Comment by cyberbobcity** [comment]
That is what I did, it says it’s not able to be used on the device. I hit continue to proceed but it doesn’t download.

**Comment by cyberbobcity** [comment]
I found this page with old versions, but not sure what version I should try: https://chrome.en.uptodown.com/android/old

**Comment by jimpastos** [comment]
https://androidapksfree.com/chrome/com-android-chrome/old/
It appears 71 is the latest version supported. Wink Relays runs on Android 4.3.
Seems you can only get up to this:
https://androidapksfree.com/chrome/com-android-chrome/download-old/chrome-71-0-3578-99-357809900-android-4-1-apk-download/

**Comment by cyberbobcity** [comment]
Awesome! I’m going to try this out right when I get home. The Wink Relay works so much better now using MQTT and Home Assistant than the Wink Hub. No more delay. Thanks for all your hard work!
