### ISSUE TITLE
Post-Install wink requires login and forces update

### ISSUE THREAD

**Issue by ATor69** [jimpastos/wink-relay-manager#13]
I am recently looking into rooting two relays and installing wink-relay-manager.  I've walked through the process without issue, but after everything is said and done, on my final reboot I am presented with the Wink 'Login/Sign Up' screen with no other options.  Upon logging in to get past this screen the unit then updates, negating all the of the work done.  Is there a step I am missing that would circumvent the login requirement while still allowing access to the Wink screen as you show in your readme? Or Am I misunderstanding and should have installed/swapped to a different loader to avoid Wink showing up on reboot?

**Comment by jimpastos** [comment]
I haven't done this process recently, but you should definitely not log in.
Another user (@jun3280net) posted a good article with steps recently.
Try these out:
https://community.home-assistant.io/t/wink-relay-guide-to-migrate-to-home-assistant-with-reference-to-smartthings-hubitat/196464

**Comment by ATor69** [comment]
Thanks Jim, following that guide is what landed me with this issue 🤣 but I
figured it out with a combination of a few guides, and logging in before
the root process to get all the updates completed.
