### ISSUE TITLE
Cannot locate symbol "__read_chk"

### ISSUE THREAD

**Issue by yanxke** [jimpastos/wink-relay-manager#19]
After following the install instructions, I'm not getting updates on mqtt and no logs on the local device.  While trying to run it directly, I'm getting the following error:

CANNOT LINK EXECUTABLE: cannot locate symbol "__read_chk" referenced by "./edisonwink"...

**Comment by jimpastos** [comment]
Did you build yourself or download the pre compiled binary?

**Comment by yanxke** [comment]
I did my own build using the latest NDK and got that error.  Using your precompiled release works now.  Thanks!
