### ISSUE TITLE
How to root my device?

### ISSUE THREAD

**Issue by NDNELSON** [jimpastos/wink-relay-manager#4]
Hi sorry but I’m completely New in this topics. Could you  give me a way to root my wink relay device?

**Comment by jimpastos** [comment]
If you managed to install APKPure, you can install Kingroot and root from there. More info here:
http://thingsthataresmart.wiki/index.php?title=Wink_Relay

You can skip 2.6 part as this project replaces that

**Comment by NDNELSON** [comment]
Just one question. The motion sensor of wink relay still working for turn off and turn on screen depending on presence? Does device runs Android normally after root?
