### ISSUE TITLE
Many doubts what I have

### ISSUE THREAD

**Issue by NDNELSON** [jimpastos/wink-relay-manager#5]
Just one question. The motion sensor of wink relay still working for turn off and turn on device screen depending on presence? Does device runs Android normally after root?

**Comment by NDNELSON** [comment]
And to install this software is necessary to Connect wink relay through usb or it is posible to run through tcp adb ?

**Comment by NDNELSON** [comment]
Ok so I just open Android studio with this project clone and after root my device and and adb connect just type  Run ./build.sh to install in wink relay?

**Comment by jimpastos** [comment]
You can download a release directly and avoid building. 

Just download the latest wink_manager from the Releases tab and just push it to the device

adb connect <ip>
adb push wink-manager /sdcard

You probably want to push an .ini file too

then (assuming you rooted your device) follow the Install steps in the README
adb shell
su
... rest of the steps

**Comment by NDNELSON** [comment]
Thanks finally the .ini file pushes in the same directory  /sdcard ?

**Comment by jimpastos** [comment]
Yes

**Comment by jimpastos** [comment]
What mqtt prefix did you set in your ini file? The default is "Relay" so the topics will be: 
Relay/relays/0/state
Relay/relays/1/state

**Comment by NDNELSON** [comment]
I can make it work for one week but today I realized that wink app askme to sign through their app agan and mqtt control stop working. What happen? ¿What Can I do?

**Comment by jimpastos** [comment]
How did their app start? Also did you run all the right disable commands in the README? Did you replace the edisonwink file correctly?

**Comment by NDNELSON** [comment]
I just reboot my wink rwlay and it works again but now I disable all winks app and widgets and it works again. 
Another question how can I modify the sensibility motion sensor because I have to put my finger on the sensor for screen turn on, I would like more sensibility
