### ISSUE TITLE
possible reboot via MQTT?

### ISSUE THREAD

**Issue by jaburges** [jimpastos/wink-relay-manager#7]
Hey there, firstly thanks again for building this - using 4 relays in the house and all SOLID! 

only issue is when i reboot my 'hub' (Home Assistant) I often need to reboot the Wink Relays. I run my setup in docker on a synology NAS, so using adb (without installing on the host) is quick tough, so wondering how hard it would be to add a command that on receipt of a specific topic would reboot the Wink Relays. 
I can then put an automation related to the hub restarting, that it will sequentially reboot the Relays in the house? 

Just a thought, but not sure if anyone else would find it useful? (i also dont know where to start with this, otherwise i'd give it a go myself and share) 

Appreciate any insight too

**Comment by jimpastos** [comment]
I guess this is doable and probably a good thing to have. Ill look into when I have time.
Why do you need to reboot the relays after restarting other devices? Does the mqtt connection not recover?

**Comment by jimpastos** [comment]
I have my Home Assistant (rpi) reboot every night at 3-4 am. My relays recover and reconnect without intervention.

**Comment by jaburges** [comment]
thank you :) 
I have the browser auto-start to specific 'tabs' of the lovelace UI so will manage the downstream portion, but the reboot i find is needed after i change something on the lovelace UI HA side. It needs manually refreshing on all the wink relays (or a quick reboot brings up any changes)

**Comment by jimpastos** [comment]
I see. I have a very similar setup. Restarting the whole relay sounds rather crude but hey... it works :)

What browser are you using? I am using fullscreen chrome and i usually just pull to refresh. Have you done any hacks to remove the heading/menus for lovelace?

I wonder if there is some kind integration that can happen to force the browser to reload.

**Comment by jaburges** [comment]
I use an Autostart App - interestingly if i load the page from Chrome directly I get the bar at the top. 
However, if I pin it to the home screen, close Chrome and launch from the home screen icon = no bar.

I also have 4 of these (and been restarting regularly as I update HA - and now node-red too).

Browser reload would be more efficient as getting a stale UI is really the only thing from making this the perfect solution with MAX WAF points ;)

**Comment by jimpastos** [comment]
Added support in v1.2

**Comment by jaburges** [comment]
@jimpastos just coming back to say how useful this is. 
Realized that sometimes my relays stop reporting temp/humidity. So in node-red now if state = unknown - reboot 
WINNER! thanks again
